name: Update Wind Data and Calendar

on:
  schedule:
    # Run twice a day, e.g., at 05:00 and 17:00 UTC
    # Adjust times based on GFS availability and your needs
    - cron: '0 5,17 * * *'
  # Optional: Add workflow_dispatch to run manually from GitHub Actions tab
  workflow_dispatch:

jobs:
  run_update_process:
    runs-on: ubuntu-latest # Or a different runner if needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Use your desired Python version

      - name: Install system dependencies (for cfgrib)
        run: |
          sudo apt-get update
          sudo apt-get install -y libeccodes-dev

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          # Install packages listed in requirements.txt (including cfgrib, xarray, etc.)
          pip install -r scripts/requirements.txt


      - name: Create data directory
        run: mkdir gfs_wind_data # Matches the output_directory in your script

      - name: Run Download Script
        run: python scripts/gfs_downloader.py

      - name: Run Analyzer Script
        run: python scripts/gfs_analyzer.py

      - name: Run Calendar Script
        run: python scripts/create_calendar.py forecast_combined.json 7

      - name: Upload Calendar File via SFTP (using dedicated SFTP Action)
        uses: wangyucode/sftp-deploy@v2.0.0
        with:
          host: ${{ secrets.FTP_SERVER }}
          port: 5544
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          localPath: './lat47.128lon7.229kn7.ics'
          remotePath: '/project7iii.com/public_html/foildata/'
        env:
          CI: true